### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by mblue9**
Some small edits to text.

One question:
Is this palette colour selection similar to what you do for tidyheatmap default?
`colours <- c("#440154FF", "#21908CFF", "#fefada" )`
as I added in a comparison of how to generate a heatmap of variable genes with base R (based on code in our previous RNA-seq workshop [here](http://combine-australia.github.io/RNAseq-R/06-rnaseq-day1.html))

And one comment:
I saw you had changed the exercise code to 
`pasilla %>% 
  tidybulk(sample, symbol, `count normalised adjusted`)`
but I've changed it back to 
`pasilla %>% 
  tidybulk()`
as I'm not using the tidyheatmap pasilla data, I ended up creating a Summarizedexperiment object from the raw pasilla counts i.e. they're not already normalised and added it to the workshop package. As I think it makes more sense to start from raw counts to try out the commands shown in the workshop (and otherwise tidybulk would end up scaling the already normalised counts)

### CODE REVIEW

**Comment by stemangiola** [comment]
Hello Maria,

this is the default palette

c("#440154FF", "#21908CFF", "#fefada" )

**Review by stemangiola — APPROVED** [review]

**Comment by stemangiola** [comment]
Sorry I should have waited. The build check in master now gives ERROR. It's not so easy to decode, something to do with tidyr.

**Comment by mblue9** [comment]
waited for what? I don't think you did anything wrong. I think the issue is some dependencies have new versions:
```Run remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
tibble     (3.0.1   -> 3.0.2 ) [CRAN]
Rcpp       (1.0.4.6 -> 1.0.5 ) [CRAN]
GetoptLong (1.0.1   -> 1.0.2 ) [CRAN]
limma      (3.45.7  -> 3.45.8) [CRAN]
```

I think Rcpp update may be the culprit as see the 3rd last line here:

```Quitting from lines 100-118 (tidytranscriptomics.Rmd) 
Error: processing vignette 'tidytranscriptomics.Rmd' failed with diagnostics:
package or namespace load failed for 'tidyr' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so':
  /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so: undefined symbol: EXTPTR_PTR
--- failed re-building ‘tidytranscriptomics.Rmd’
```

I'll see if I can test it locally and find any workaround.

**Comment by stemangiola** [comment]
waited for local checks before merging, in theory the master should be problems free if we can catch them at pull-request time. Instead I have merged before the checks finished.

**Pull request merged**
