### PR TITLE
Few edits

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by stemangiola** [comment]
With the Docker I was unable to run the command line on Windows. Nothing happened and I got bored.

Please confirm if with new github instructions you a able to install the whole thing

**Comment by mblue9** [comment]
Hey good news! I just tested that install from Github & seems to work well, at least code all ran & I didn't spot any obvious errors.
One minor question - I had to copy/paste from the vignette to run the code & the code is interleaved with text so it's quite a number of separate copy/pastes. Instead should we tell them they can copy/paste the code (i.e just one copy/paste) from here: https://raw.githubusercontent.com/stemangiola/bioc_2020_tidytranscriptomics/master/vignettes/tidytranscriptomics.Rmd

**Comment by mblue9** [comment]
Also I get this but not sure if we can do anything about that?
```
Warning message:
`group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

**Comment by stemangiola** [comment]
> 
> 
> Hey good news! I just tested that install from Github & seems to work well, at least code all ran & I didn't spot any obvious errors.
> One minor question - I had to copy/paste from the vignette to run the code & the code is interleaved with text so it's quite a number of separate copy/pastes. Instead should we tell them they can copy/paste the code (i.e just one copy/paste) from here: https://raw.githubusercontent.com/stemangiola/bioc_2020_tidytranscriptomics/master/vignettes/tidytranscriptomics.Rmd

True. Feel free to add it to the instructions in the README

**Comment by stemangiola** [comment]
> 
> 
> Also I get this but not sure if we can do anything about that?
> 
> ```
> Warning message:
> `group_by_()` is deprecated as of dplyr 0.7.0.
> Please use `group_by()` instead.
> See vignette('programming') for more help
> This warning is displayed once every 8 hours.
> Call `lifecycle::last_warnings()` to see where this warning was generated. 
> ```

Yes although I never used group_by_ I might have used group_by_at or something, while dplyr now uses a smarter system. Where do you get this from?

**Comment by mblue9** [comment]
It appears as the end when I ran all the code but not sure what exactly is triggering it, I've seen it before when testing the workshop & meant to tell you but forgot
```+   scale_y_log10()+
+   theme_bw()
> 
> strip_chart
> 
> strip_chart %>% ggplotly(tooltip = c("label", "y"))
Warning message:
`group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
> 
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6
```

**Comment by mblue9** [comment]
Ah I think the warning comes from plotly https://github.com/ropensci/plotly/issues/1786

**Comment by stemangiola** [comment]
> 
> 
> Ah I think the warning comes from plotly [ropensci/plotly#1786](https://github.com/ropensci/plotly/issues/1786)

In this case is not in our hands. We could hide warnings through R markdown for that block

**Comment by mblue9** [comment]
Ah yes I had already hidden the warning for that in the Rmarkdown (tired so forgot), so another good reason to suggest they copy/paste from our Rmarkdown here https://raw.githubusercontent.com/stemangiola/bioc_2020_tidytranscriptomics/master/vignettes/tidytranscriptomics.Rmd

**Comment by mblue9** [comment]
Just testing the copy paste from the Rmarkdown and works well exceot the logo block triggers an error as the file can't be accessed. Do you know if I add eval=FALSE will the logo still show up in the rendered workshop website or should I move the logo to the README instead?

```
{r, eval=FALSE, echo=FALSE, out.width = "200px"}
knitr::include_graphics("../inst/vignettes/tidybulk_logo.png")
```

**Comment by stemangiola** [comment]
> 
> 
> Just testing the copy paste from the Rmarkdown and works well exceot the logo block triggers an error as the file can't be accessed. Do you know if I add eval=FALSE will the logo still show up in the rendered workshop website or should I move the logo to the README instead?
> 
> ```
> {r, eval=FALSE, echo=FALSE, out.width = "200px"}
> knitr::include_graphics("../inst/vignettes/tidybulk_logo.png")
> ```

I think eval=FALSE will kill the logo.

I think users should now execute all code blindly but execute chunk by chunk

**Comment by mblue9** [comment]
I agree chunk by chunk is better, it's just that with such short time for this workshop it would be a shame if some spent time wondering about errors that aren't important. But if you like the logo there instead of in the README I'll leave it.

**Review by mblue9 — APPROVED** [review]

**Comment by stemangiola** [comment]
> 
> 
> I agree chunk by chunk is better, it's just that with such short time for this workshop it would be a shame if some spent time wondering about errors that aren't important. But if you like the logo there instead of in the README I'll leave it.

If we manage to put the image inside the package we could solve both problems. no?

**Comment by mblue9** [comment]
>If we manage to put the image inside the package we could solve both problems. no?

Sounds good, how do we do that?

**Pull request merged**
