### PR TITLE
Almost final edits

### PR DESCRIPTION
**Pull request by mblue9**
Some tweaks, also added an image to show the rna-seq steps & where tidybulk fits, not sure what it'll look like in the website, see what you think maybe you can do better :)

### CODE REVIEW

**Comment by mblue9** [comment]
Seems we're only allowed to list one person as maintainer so I put you.

```
 checking DESCRIPTION meta-information ... ERROR
Authors@R field gives more than one person with maintainer role:
...
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

**Comment by stemangiola** [comment]
> eps &

great! It could be bigger

**Comment by mblue9** [comment]
yes I'll try to make bigger but converting to eps makes it quite large 6MB (original png was 105KB) do you know a way to generate a smaller eps (original file is just an annotated screenshot png & I don't have any fancy image editing program so I tried using this https://image.online-convert.com/convert-to-eps)

**Comment by stemangiola** [comment]
send me the source file, I will try to replicate in illustrator. it will be super quick

**Pull request merged**
