### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by mblue9**
Some small changes and I've added a supplementary file with things we omitted. Let me know what you think or feel free to edit.
- Add filter step to heatmap
- Add more info to install instructions
- Make README nicer like https://github.com/waldronlab/PublicDataResour… …
- Make website nicer like https://waldronlab.io/PublicDataResources/
- Make figures in vignette less squished
- Add no need to run base R code
- Add how to contribute or ask questions
- Add Stefano to maintainers
- Add supplementary material

### CODE REVIEW

**Comment by mblue9** [comment]
I'll merge this to see how it looks and we can revert or make any additional changes.

**Comment by stemangiola** [comment]
> 
> 
> I'll merge this to see how it looks and we can revert or make any additional changes.

Dangerous move! XD

**Comment by mblue9** [comment]
Yup living on the edge :smile:. But better to experiment now than Monday night.

**Comment by mblue9** [comment]
I think it looks better now but see what you think & feel free to make edits. Need to fix some little things e.g not sure how to get your name to also show up as Developer at the bottom of the page here: https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/tidytranscriptomics.html

**Comment by stemangiola** [comment]
What has changed exactly?

**Comment by mblue9** [comment]
Ah it's mainly just small changes to layout in the README and workshop but wasn't 100% sure if they'd work. And adding the Supplementary file and menu access at the top of the workshop:
Screen Shot 2020-07-25 at 12 33 46 pm

**Comment by stemangiola** [comment]
Yes that's great. For the developer thing does not matter.

I'm already imagining the website with the tabs for 30mins 1h 2h workshops. That would be really "sellable" and we might get bigger calls.

And the package tidysc is on its way ;)

**Pull request merged**
