### PR TITLE
Change figure and small edits

### PR DESCRIPTION
**Pull request by mblue9**
Ok see what you think now.
Last things to do:
- I added one idea for how to do tidy pathway analysis (that has visualisation) to supplementary.Rmd file are you ok with that or want to make changes?
- Can you edit the "About" for the repo as per recommendation from Bioc2020 (only repo owner can do that) e.g. add a little text & website link like the panel on the right here: https://github.com/iSEE/iSEEWorkshop2020/

### CODE REVIEW

**Comment by mblue9** [comment]
Merging to see what the image looks like in the website.

**Comment by stemangiola** [comment]
Wow incredible how good looking is the website. Also our setup is really good!

**Comment by mblue9** [comment]
Yes the website is looking good! 😄Nice job on the figure!

**Comment by stemangiola** [comment]
The hexagonal logos could be half of the size in README and workshop, would be more elegant.

**Comment by mblue9** [comment]
Done! https://github.com/stemangiola/bioc_2020_tidytranscriptomics/pull/37

**Pull request merged**
